name: googletask
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  provider: ^2.0.1
  cloud_firestore:
  #cloud_firestore: ^0.13.6
  #firebase: ^7.3.0
  #firebase_core: ^0.2.5       # This dependency was added during initial configuration.
  #firebase_analytics: ^1.0.4  # add dependency for Google Analytics for Firebase


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/first_empty.jpg
    - images/task_intro.jpg
    - images/peng.jpg
    - images/pengHi.jpg